import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const svgs=['hero','github-stats','github-stats-mobile','contribution-activity','contribution-activity-mobile','languages','recent-projects','recent-projects-mobile','public-projects','public-projects-mobile','private-projects','private-projects-mobile','e-vms','hoo-bank'].map((name)=>`assets/${name}.svg`);
const required=['README.md','README.template.md','PROFILE_SYSTEM.md','data/projects.json','data/stats.json','assets/e-vms-logo.png','scripts/generate-profile.mjs','scripts/github-stats.mjs','tests/github-stats.test.mjs','.github/workflows/refresh-profile.yml',...svgs];
for(const file of required)if(!fs.existsSync(path.join(root,file)))throw new Error(`Missing required file: ${file}`);
const manifest=JSON.parse(fs.readFileSync(path.join(root,'data/projects.json'),'utf8'));
const stats=JSON.parse(fs.readFileSync(path.join(root,'data/stats.json'),'utf8'));
const readme=fs.readFileSync(path.join(root,'README.md'),'utf8');
const workflow=fs.readFileSync(path.join(root,'.github/workflows/refresh-profile.yml'),'utf8');
const projects=manifest.projects;
const fields=['repository','category','visibility','includeInStats','includeInLanguages','includeInActivity','includeInPortfolio','displayName','description','image','relatedRepositories','attribution'];
for(const project of projects)for(const field of fields)if(!(field in project))throw new Error(`Manifest field missing: ${field}`);
if(projects.filter((p)=>p.category==='skillAura').length!==12||projects.filter((p)=>p.category==='skillAura'&&p.visibility==='public').length!==8||projects.filter((p)=>p.category==='skillAura'&&p.visibility==='private').length!==4)throw new Error('SkillAura scope mismatch');
if(projects.filter((p)=>p.category==='fork').length!==1||projects.filter((p)=>p.category==='external').length!==1||projects.filter((p)=>p.category==='external-related').length!==2)throw new Error('Separated portfolio scope mismatch');
const uniqueRepositories=new Set(projects.map((p)=>`${p.owner}/${p.repository}`));
if(uniqueRepositories.size!==projects.length)throw new Error('Duplicate repository identity in manifest');
const externalRepositories=projects.filter((p)=>p.category==='external'||p.category==='external-related');
if(externalRepositories.length!==3||externalRepositories.some((p)=>!p.includeInStats||!p.includeInActivity||p.includeInLanguages||p.portfolioProjectId!=='e-vms'))throw new Error('External professional activity scope mismatch');
if(stats.schemaVersion!==6||stats.scope.statsProjects!==15||stats.scope.externalRepositories!==3)throw new Error('Generated stats schema or scope mismatch');
if(stats.categorySummary.skillAura.repositories!==12||stats.categorySummary.externalProfessional.repositories!==3||stats.categorySummary.totalTracked.repositories!==15||stats.categorySummary.forkDerived.includedInAggregate!==false)throw new Error('Category summary scope mismatch');
for(const key of ['allTimeDefaultBranchCommits','currentYearCommits','rollingCommits','last90DaysCommits','last30DaysCommits','pullRequests','issues','activeRepositories12Months'])if(stats.categorySummary.skillAura[key]+stats.categorySummary.externalProfessional[key]!==stats.categorySummary.totalTracked[key])throw new Error(`Category totals do not reconcile: ${key}`);
for(const key of ['stars','allTimeDefaultBranchCommits','currentYearCommits','last90DaysCommits','last30DaysCommits','pullRequests','issues','activeRepositories12Months'])if(!Number.isInteger(stats.githubStats[key])||stats.githubStats[key]<0)throw new Error(`Invalid metric: ${key}`);
for(const key of ['rollingCommits','contributionDays','currentStreak','longestStreak'])if(!Number.isInteger(stats.contributionActivity[key])||stats.contributionActivity[key]<0)throw new Error(`Invalid contribution metric: ${key}`);
if(stats.contributionActivity.monthly.length!==12)throw new Error('Monthly trend must contain twelve real months');
if(stats.contributionActivity.monthlySkillAura.length!==12||stats.contributionActivity.monthlyExternal.length!==12)throw new Error('Category monthly trends must contain twelve real months');
for(const month of ['2026-08','2026-09','2026-10']){const row=stats.activity.monthlyFocus.find((item)=>item.month===month);if(!row||row.total!==row.skillAura+row.externalProfessional)throw new Error(`Invalid focused monthly activity: ${month}`);}
if(stats.externalPortfolio.owner!=='Evisionindia'||stats.externalPortfolio.repositories.length!==3||new Set(stats.externalPortfolio.repositories).size!==3)throw new Error('E-VMS aggregate identity mismatch');
if(stats.externalPortfolio.allTimeDefaultBranchCommits!==stats.projects.filter((p)=>p.portfolioProjectId==='e-vms').reduce((sum,p)=>sum+p.allTimeDefaultBranchCommits,0))throw new Error('E-VMS aggregate double-count or omission');
if(/\{\{[A-Z_]+\}\}/.test(readme))throw new Error('Unresolved README placeholder');
if(/audit|compliance|approved project scope|token policy|repository-level metrics|evidence classification/i.test(readme))throw new Error('Public README contains internal process language');
if(/https:\/\/github\.com\/Skill-Aura-Official\/(kiru|SSB|nyther-userbot|TenderIQ)/i.test(readme))throw new Error('Private repository URL exposed');
for(const marker of ['Total Tracked Portfolio Activity','Contribution Activity','SkillAura Language Footprint','Technology Footprint','Recently Updated Projects','SkillAura Project Directory','Private / Closed-Source Projects','E-VMS · External Professional Work','Forked / Derived Work'])if(!readme.includes(marker))throw new Error(`README section missing: ${marker}`);
if(/external work (and|\+) fork excluded|external work excluded/i.test(readme))throw new Error('README incorrectly excludes approved external work');
if(!workflow.includes('cron: "17 */6 * * *"')||!workflow.includes('workflow_dispatch:')||!workflow.includes('PROFILE_DATA_TOKEN: ${{ secrets.SKILLAURA_PROFILE_TOKEN }}'))throw new Error('Refresh workflow mismatch');
for(const file of svgs){const content=fs.readFileSync(path.join(root,file),'utf8');if(!content.startsWith('<svg')||!content.includes('<title')||!content.includes('<desc'))throw new Error(`Invalid accessible SVG: ${file}`);}
const repositoryText=required.filter((file)=>!file.endsWith('.png')).concat(['package.json','.gitignore']).map((file)=>fs.readFileSync(path.join(root,file),'utf8')).join('\n');
if(/gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----/.test(repositoryText))throw new Error('Potential credential material detected');
const blocked=['YXVyb3JhLWluay1nZW5pZQ==','dHV0b3I=','Vk1TLUFJLUFuYWx5dGljcw==','Y2N0di12bXMxMA=='].map((v)=>Buffer.from(v,'base64').toString('utf8'));
for(const name of blocked)if(repositoryText.includes(name))throw new Error('Excluded repository reference found');
const restricted=Buffer.from('SW5ub3ZhdGhvbg==','base64').toString('utf8');
if(new RegExp(`(^|[^-\\w])${restricted}([^\\w-]|$)`,'m').test(repositoryText.replaceAll('Innovathon-Public','')))throw new Error('Excluded private repository reference found');
console.log('SkillAura profile validation passed.');
